name: Deploy Client

on:
  push:
    branches: [main]

defaults:
  run:
    working-directory: ./client

jobs:
   build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install caprover
      run: sudo npm install -g caprover

    - name: Install dependencies
      run: yarn install --non-interactive

    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1
      with:
        envkey_VITE_API_URL: ${{secrets.API_URL}}
        envkey_VITE_API_VERSION: v1
        envkey_VITE_SENTRY: ${{secrets.SENTRY}}

    - name: Compile assets
      run: yarn build

    - name: Create tar
      run: tar -cvf deploy.tar captain-definition dist/*

    - name: Deploy
      run: caprover deploy -h ${{ secrets.CAPROVER_SERVER_PROD }} -p ${{ secrets.CAPROVER_PASSWORD_PROD }} -a spotify-liked -t ./deploy.tar